// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://datwubjybmameqxywtfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhdHd1Ymp5Ym1hbWVxeHl3dGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjY5NDYsImV4cCI6MjA2OTkwMjk0Nn0.qlor1X-D359q9MC25CSNfbUPIfcM-AzxdAiVJWJ3svs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});